# Generated by Django 3.1.2 on 2020-10-30 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField()),
                ('data_criacao', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('apelido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('apelido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDetalhe',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipamento',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TipoOrdemServico',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('fabricante', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('patrimonio', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100)),
                ('identificacao', models.CharField(max_length=100)),
                ('qr_code', models.IntegerField()),
                ('proprietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipamentos.proprietario')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipamentos.tipoequipamento')),
            ],
        ),
        migrations.CreateModel(
            name='Detalhe',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, null=True)),
                ('nome_fantasia', models.CharField(max_length=100, null=True)),
                ('superior', models.CharField(max_length=100, null=True)),
                ('cnpj', models.CharField(max_length=20, null=True)),
                ('observacoes', models.TextField(max_length=500, null=True)),
                ('contato', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('telefone1', models.CharField(max_length=20, null=True)),
                ('ramal1', models.CharField(max_length=20, null=True)),
                ('telefone2', models.CharField(max_length=20, null=True)),
                ('ramal2', models.CharField(max_length=20, null=True)),
                ('fax', models.CharField(max_length=20, null=True)),
                ('cep', models.CharField(max_length=12, null=True)),
                ('rua', models.CharField(max_length=100, null=True)),
                ('numero', models.IntegerField(null=True)),
                ('bairro', models.CharField(max_length=100, null=True)),
                ('cidade', models.CharField(max_length=100, null=True)),
                ('estado', models.CharField(max_length=2, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='equipamentos.empresa')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipamentos.tipodetalhe')),
            ],
        ),
        migrations.CreateModel(
            name='ChamadoEquipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_prioridade', models.CharField(max_length=100)),
                ('prioridade', models.PositiveSmallIntegerField()),
                ('get_prioridade', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('get_solicitante', models.CharField(max_length=100)),
                ('get_equipamento_servico', models.CharField(max_length=100)),
                ('get_criticidde', models.CharField(max_length=100)),
                ('chamado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipamentos.chamado')),
            ],
        ),
        migrations.AddField(
            model_name='chamado',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipamentos.equipamento'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='id_tipo_ordem_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipamentos.tipoordemservico'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='problema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipamentos.problema'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipamentos.solicitante'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='tipo_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipamentos.tiposervico'),
        ),
    ]
